$(function(){
	$(".about").fadeIn(1000);
});

$(function(){
	$(".nav_1").click(function(){
		window.location.href="#slide1";
		$(".about").css("display","none");
		$(".about").fadeIn(1000);
	});
});

$(function(){
	$(".nav_2").click(function(){
		window.location.href="#slide2";
		$(".hider").css("display","none");
		$(".hider").fadeIn(1000);
		$("#list1").animate({width:"80%"},2000);
		$("#list2").animate({width:"50%"},2000);
		$("#list3").animate({width:"40%"},2000);
		$("#list4").animate({width:"35%"},2000);
		$("#list5").animate({width:"30%"},2000);
	});
});

$(function(){
	$(".nav_3").click(function(){
		window.location.href="#slide3";
		$(".Education").css("display","none");
		$(".Education").fadeIn(1000);
		$("#major2,#major3,#major4").mouseenter(function(){
			$(this).animate({top:"-10px"},500);
		});
		$("#major2,#major3,#major4").mouseleave(function(){
			$(this).animate({top:"0"},500);
		});
	});
});

$(function(){
	$(".nav_5").click(function(){
		window.location.href="#slide4";
		$(".reason").css("display","none");
		$(".reason").fadeIn(1000);
	});
});

$(function(){
	$(".nav_4").click(function(){
		window.location.href="#slide5";
		$(".demo").css("display","none");
		$(".demo").fadeIn(1000);
	});
});

$(function(){
	$("#reason_tab_bar1").click(function(){
		$(".reason_tab_list2").css("display","none");
		$(".reason_tab_list1").css("display","block");
		$("#reason_tab_bar1").css({background:"#fff",color:"#993366"});
		$("#reason_tab_bar2").css({background:"none",color:"#fff"});
	});
});

$(function(){
	$("#reason_tab_bar2").click(function(){
		$(".reason_tab_list1").css("display","none");
		$(".reason_tab_list2").css("display","block");
		$("#reason_tab_bar2").css({background:"#fff",color:"#993366"});
		$("#reason_tab_bar1").css({background:"none",color:"#fff"});
	});
});

$(function(){
	$(".nav_1").mouseenter(function(){
		$(".nav_info1").show(200);
	});
});
$(function(){
	$(".nav_1").mouseleave(function(){
		$(".nav_info1").hide(200);
	});
});
$(function(){
	$(".nav_2").mouseenter(function(){
		$(".nav_info2").show(200);
	});
});
$(function(){
	$(".nav_2").mouseleave(function(){
		$(".nav_info2").hide(200);
	});
});
$(function(){
	$(".nav_3").mouseenter(function(){
		$(".nav_info3").show(200);
	});
});
$(function(){
	$(".nav_3").mouseleave(function(){
		$(".nav_info3").hide(200);
	});
});
$(function(){
	$(".nav_4").mouseenter(function(){
		$(".nav_info4").show(200);
	});
});
$(function(){
	$(".nav_4").mouseleave(function(){
		$(".nav_info4").hide(200);
	});
});
$(function(){
	$(".nav_5").mouseenter(function(){
		$(".nav_info5").show(200);
	});
});
$(function(){
	$(".nav_5").mouseleave(function(){
		$(".nav_info5").hide(200);
	});
});